export default  {
    CHANGE_SUBMISSION_STATUS:'CHANGE_SUBMISSION_STATUS',
    CHANGE_SUBMISSION:'CHANGE_SUBMISSION',
    CLEAR_SUBMISSION:'CLEAR_SUBMISSION',

    SUBMISSION_STATUS:{
        NONE:'NONE',
        
        SELECTION:'SELECTION',
        CLEARANCE:'CLEARANCE',

        EDIT:'EDIT',
        CREATING:'CREATING',
        
        REVIEW:'REVIEW',
        QUOTE:'QUOTE'
    }
}