export const SIGNUP_STATUS = 'SIGNUP_STATUS'
export const FETCH_SUBMISSIONS = 'FETCH_SUBMISSIONS'
export const EDIT_SUBMISSION = 'EDIT_SUBMISSION'

export const CHANGE_SUBMISSION_STATUS = 'CHANGE_SUBMISSION_STATUS'
export const CHANGE_SUBMISSION = 'CHANGE_SUBMISSION'
export const CHANGE_SUBMISSION_PARAMS = 'CHANGE_SUBMISSION_PARAMS'
export const CLEAR_SUBMISSION = 'CLEAR_SUBMISSION'
export const CHANGE_CLEARANCE_INFO = 'CHANGE_CLEARANCE_INFO'

export const SUBMISSION_STATUS = {
  NONE: 'NONE',
  SELECTION: 'SELECTION',
  CLEARANCE: 'CLEARANCE',
  EDIT: 'EDIT',
  CREATING: 'CREATING',
  REVIEW: 'REVIEW',
  QUOTE: 'QUOTE'
}