export const SIGNUP_STATUS = 'SIGNUP_STATUS'
export const FETCH_SUBMISSIONS = 'FETCH_SUBMISSIONS'
export const EDIT_SUBMISSION = 'EDIT_SUBMISSION'

export const CHANGE_SUBMISSION_STATUS = 'CHANGE_SUBMISSION_STATUS'
export const CHANGE_SUBMISSION = 'CHANGE_SUBMISSION'
export const CHANGE_SUBMISSION_PARAMS = 'CHANGE_SUBMISSION_PARAMS'
export const CLEAR_SUBMISSION = 'CLEAR_SUBMISSION'

export const SUBMISSION_CLEARANCE_FAILED = 'submission/CLEARANCE_FAILED'
export const SUBMISSION_CLEARANCE_PASSED = 'submission/CLEARANCE_PASSED'
export const SUBMISSION_CLEARANCE_PENDING = 'submission/CLEARANCE_PENDING'
export const SUBMISSION_QUOTED = 'submission/SUBMISSION_QUOTED'
export const SUBMISSION_KNOCKED_OUT = 'submission/SUBMISSION_KNOCKED_OUT'
export const SUBMISSION_FAILED = 'submission/SUBMISSION_FAILED'
export const SUBMISSION_CREATE = 'submission/SUBMISSION_CREATE'
export const SUBMISSION_EDIT = 'submission/SUBMISSION_EDIT'

export const SUBMISSION_STATUS = {
  NONE: 'NONE',
  SELECTION: 'SELECTION',
  CLEARANCE: 'CLEARANCE',
  EDIT: 'EDIT',
  CREATING: 'CREATING',
  REVIEW: 'REVIEW',
  QUOTE: 'QUOTE'
}