version: 0.1

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Setting production env variables...
      - npm run gulp transform:prod
  build:
    commands:
      - echo Building deployment assets...
      - npm run gulp build
artifacts:
  files:
    - 'node_modules/**/*'
    - 'dist/**/*'
