# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: sudo su -c 'echo "deb http://deb.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'

      - run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt install -t jessie-backports  openjdk-8-jre-headless ca-certificates-java
      - run:
          name: "Testing Java"
          command: "java -v"

      - run:
          name: "Testing node"
          command: "node -v"

      - run:
          name: "Run E2E"
          command: "npm run e2e"

      - run:
          name: "Success"
          command: echo "success"

